### ISSUE TITLE
Warning: Error in read.table: more columns than column names

### ISSUE THREAD

**Issue by hchen725** [ParkerICI/scgraphs#3]
Files were clustered with grappolo.
When attempting to read the files into vite, this error comes up:

Warning: Error in read.table: more columns than column names
  47: stop
  46: read.table
  45: <observer> [C:\Users\XXX\Documents\R\win-library\3.4\vite\shinyGUI/server.R#151]
   2: shiny::runApp
   1: vite_GUI

What causes this issue and what's the best way to fix it?

**Comment by luglilab** [comment]
I had the same issue, i solved the problems changing the columns name.

**Comment by pfgherardini** [comment]
Sorry for the late reply. Can you send me via Dropbox or Box an example of the files that are failing? Both the input files before clustering as well as the clustered files?

Thanks

Federico
