### ISSUE TITLE
Creating landmarks

### ISSUE THREAD

**Issue by algebio** [ParkerICI/scgraphs#4]
Hi Federico

I'm trying to build my own landmark file but unlike the sample data from ParkerICI to try Scaffold, I use different cytof panels for every cell type (T cells, B cells, etc)

Is there any way to use all these fcs files generated from different panels to create a single landmark file?

Thanks
Juan

**Comment by pfgherardini** [comment]
Hi Juan,

No unfortunately it's not possible. You would have to limit yourself to only using the markers that are common to all the files. There is really no method that I can think of that would enable what you are describing
