### ISSUE TITLE
Bug report - complete_forceatlas2test - overlap_method

### ISSUE THREAD

**Issue by ghaithcode** [ParkerICI/scgraphs#6]
Hello, 

I noticed that the complete_forceatlas2 function does not accept overlap.method ="expand". I debugged the issue and I found out that there is a small typo in the if statement in the   complete_forceatlas2 as follows:
     
This condition: 

> else if(overlap_method == "expand")
>             G <- adaptive_expand(G, overlap.iter)

need to be modified to: 

> else if(**overlap.method** == "expand")
>             G <- adaptive_expand(G, overlap.iter)

Thanks, 

Ghaith,

**Comment by pfgherardini** [comment]
You are right! Thank you very much for reporting and providing a fix.

Federico

**Comment by ghaithcode** [comment]
You are welcome!

GBH
-- 
*Dr. Ghaith Bany Hamad*, B.Sc., M.Sc.A., Ph.D.,
