### ISSUE TITLE
Cant install vite; command line issue?

### ISSUE THREAD

**Issue by Stein-ErikG** [ParkerICI/scgraphs#7]
Hi,

Ive managed to install both grappolo and panorama, but i cant get vite to work. I have installed xcode and apropriate command line tools. If i paste "xcode-select -p" in terminal i get a path to Xcode.app/.... . If i run "xcode-select --install" i get:
xcode-select: error: command line tools are already installed, use "Software Update" to install updates.

when i try to install: 

devtools::install_github("ParkerICI/vite")
Downloading GitHub repo ParkerICI/vite@master
✔  checking for file ‘/private/var/folders/_8/fpg279xx6lg2r8dhph4jpl0d91tsw8/T/RtmpPob3VF/remotes51833b151a/ParkerICI-vite-33cecc0/DESCRIPTION’ ...
─  preparing ‘vite’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘vite_0.4.6.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
Installing package into ‘/Users/mmasg/Library/R/3.5/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘vite’ ...
** libs
/opt/local/bin/g++-mp-4.8 -arch x86_64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/mmasg/Library/R/3.5/library/Rcpp/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from /opt/local/include/gcc48/c++/cmath:44:0,
                 from /Users/mmasg/Library/R/3.5/library/Rcpp/include/Rcpp/platform/compiler.h:100,
                 from /Users/mmasg/Library/R/3.5/library/Rcpp/include/Rcpp/r/headers.h:59,
                 from /Users/mmasg/Library/R/3.5/library/Rcpp/include/RcppCommon.h:29,
                 from /Users/mmasg/Library/R/3.5/library/Rcpp/include/Rcpp.h:27,
                 from RcppExports.cpp:4:
/opt/local/lib/gcc48/gcc/x86_64-apple-darwin13/4.8.5/include-fixed/math.h:45:23: fatal error: sys/cdefs.h: No such file or directory
 #include <sys/cdefs.h>
                       ^
compilation terminated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘vite’
* removing ‘/Users/mmasg/Library/R/3.5/library/vite’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/_8/fpg279xx6lg2r8dhph4jpl0d91tsw8/T//RtmpPob3VF/file5181d8c05ae/vite_0.4.6.tar.gz’ had non-zero exit status

**Comment by pfgherardini** [comment]
This is a MacOS specific problem not something related to the vite package 

Have you also installed gcc on your system, maybe with something like brew? It looks like it's using gcc to do the compilation, but then it can't find some of the header files installed by Xcode.

If you have indeed installed gcc try reinstalling it again.

You can find some additional info here, but it looks to me like the problem in your case is that R is not using the version of the compiler that's bundled with XCode but a separate gcc install

https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave

**Comment by pfgherardini** [comment]
try (assuming you have brew installed)

```
brew install gcc
```

**Comment by Stein-ErikG** [comment]
Hi, thank you for the quick reply. 

Indeed, i lost both brew and gcc after updating to mojave. I reinstalled everything, but it still did not work. Then i did this: 

navigate to /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg and run that package. 

I managed to install after! Thank you:)
